(** --------------------------------------------------------------------------------

	This file is part of 'PassGen'.

	'PassGen' is a random password generator.


	License:

	The MIT License (MIT)

	Copyright (c) 2017-2020 Renan Souza da Motta <renansouzadamotta@yahoo.com>

	Permission is hereby granted, free of charge, to any person obtaining a copy of
	this software and associated documentation files (the "Software"), to deal in
	the Software without restriction, including without limitation the rights to
	use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
	the Software, and to permit persons to whom the Software is furnished to do so,
	subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
	FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
	COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
	IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
	CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

	-------------------------------------------------------------------------------- **)
pass_table_6: packed array[0..TABLE_6_SIZE-1] of string = (
	// base 1024
	'alguém', 'crédito', 'bosque', 'zumbi', 'esperança', 'hiato', 'meigo', 'conserva',
	'sussurro', 'hegemonia', 'baile', 'primavera', 'copo', 'jactância', 'aprendiz', 'fosforescente',
	'hífen', 'desbotar', 'lençol', 'lápis', 'porta', 'bexiga', 'fuzil', 'genialidade',
	'poluição', 'vestido', 'olaria', 'encanto', 'derradeiro', 'higiene', 'enfeite', 'degrau',
	'justapor', 'suspeita', 'postura', 'aspas', 'glacial', 'luz', 'dengue', 'babaca',
	'intuição', 'importante', 'próximo', 'inveja', 'bezerro', 'cônsul', 'anuidade', 'churrasco',
	'piedade', 'urbano', 'ideia', 'batom', 'hálito', 'guardanapo', 'enseada', 'carroça',
	'recanto', 'jacente', 'pintar', 'harpa', 'gastronomia', 'recompensar', 'barriga', 'êxito',
	'ingresso', 'livro', 'afago', 'hispânico', 'hospital', 'plenitude', 'amanhã', 'qualidade',
	'inocência', 'quádruplo', 'depósito', 'xadrez', 'jornal', 'quórum', 'bater', 'indignação',
	'entrada', 'gasolina', 'harmonia', 'uniforme', 'vinho', 'glória', 'vítima', 'xixi',
	'ônibus', 'galáxia', 'rodapé', 'castigo', 'quintal', 'agrotóxico', 'entrevista', 'curral',
	'querosene', 'pivete', 'mocidade', 'resposta', 'atual', 'onda', 'hábil', 'banco',
	'juízo', 'dívida', 'bisnaga', 'domicílio', 'neblina', 'queixa', 'longevidade', 'desatar',
	'cúmulo', 'sertanejo', 'cutelo', 'hierarquia', 'joelho', 'futuro', 'mata', 'graça',
	'farmácia', 'aparência', 'abrigo', 'liquidação', 'glucose', 'barbante', 'assoalho', 'abismo',
	'fluminense', 'solidariedade', 'supremacia', 'juiz', 'tentação', 'zorra', 'esquina', 'identidade',
	'curva', 'loquaz', 'bandido', 'garagem', 'juventude', 'patamar', 'maluco', 'crucial',
	'quina', 'aposentado', 'fonema', 'utensílio', 'jangada', 'usuário', 'citoplasma', 'satisfação',
	'xilindró', 'zangado', 'osso', 'até', 'redondeza', 'hortaliça', 'óleo', 'susto',
	'fornalha', 'jaca', 'evidência', 'promoção', 'filho', 'quente', 'junta', 'oficina',
	'maciço', 'hectare', 'método', 'túnel', 'adiposo', 'maleta', 'plebiscito', 'justiça',
	'tijolo', 'vida', 'incentivo', 'genérico', 'miséria', 'preconceito', 'conforto', 'mensagem',
	'júbilo', 'reunião', 'pólvora', 'inteligente', 'baía', 'generosidade', 'exercício', 'buquê',
	'isonomia', 'abelha', 'botânica', 'honra', 'bermuda', 'pavimento', 'lanterna', 'apetite',
	'mordomia', 'exploração', 'orfanato', 'babá', 'chá', 'remetente', 'enxaqueca', 'jururu',
	'microfone', 'neto', 'nitidez', 'zíper', 'dourado', 'espelho', 'inseticida', 'garrafa',
	'humildade', 'vacina', 'gabar', 'bosta', 'limite', 'maldade', 'predileto', 'discreto',
	'fórmula', 'geografia', 'nada', 'arco', 'localidade', 'emotivo', 'milagre', 'batismo',
	'mofo', 'queixume', 'negligência', 'madeira', 'genética', 'tufão', 'solavanco', 'escândalo',
	'memória', 'nascente', 'flanela', 'acne', 'zinco', 'rumor', 'homem', 'impermeável',
	'firmamento', 'xilografia', 'itinerário', 'desempenho', 'zelo', 'inverno', 'mineral', 'escassez',
	'monjolo', 'pantanal', 'lâmina', 'amizade', 'aptidão', 'insano', 'falência', 'fumaça',
	'híbrido', 'equipe', 'içar', 'bloco', 'surpreendente', 'boi', 'bagatela', 'fidelidade',
	'letra', 'fertilizante', 'gabinete', 'publicidade', 'pacato', 'flagelo', 'detergente', 'roça',
	'sobrancelha', 'habilidade', 'trabalho', 'grinalda', 'minuto', 'interesse', 'mecânica', 'trânsito',
	'pimenta', 'dama', 'criança', 'benevolente', 'reticência', 'machado', 'sedentário', 'dilúvio',
	'doçura', 'álcool', 'conexão', 'circo', 'mascate', 'absoluto', 'jogo', 'infinidade',
	'pneumonia', 'represália', 'jumento', 'grama', 'analgésico', 'ducha', 'telegrama', 'detalhe',
	'gordura', 'predizer', 'diário', 'espinha', 'voluntário', 'mistura', 'opinião', 'chinelo',
	'revólver', 'incógnita', 'brasa', 'úlcera', 'mudança', 'hipertensão', 'ocioso', 'curiosidade',
	'interferência', 'zureta', 'mortal', 'duna', 'operário', 'otimismo', 'hidráulico', 'decoro',
	'guindaste', 'refeição', 'enigma', 'néctar', 'gripe', 'hélice', 'música', 'lava',
	'anotar', 'dúbio', 'superficial', 'dilema', 'riqueza', 'inédito', 'nativo', 'ácido',
	'tática', 'impossível', 'arranjo', 'novamente', 'quinzena', 'faca', 'zênite', 'volátil',
	'judicial', 'desafio', 'holocausto', 'cortiça', 'preocupação', 'natalidade', 'nordeste', 'casa',
	'porém', 'lembrança', 'liderança', 'dublagem', 'conosco', 'ostentar', 'desejo', 'quitinete',
	'manjedoura', 'muro', 'montanha', 'quarentena', 'pessoa', 'hemisfério', 'gota', 'granada',
	'lareira', 'questionário', 'roupa', 'galinha', 'estômago', 'permanecer', 'retângulo', 'eclipse',
	'pormenor', 'obra', 'banal', 'furacão', 'preposição', 'queda', 'ajuda', 'sustento',
	'açougue', 'mistério', 'capaz', 'oca', 'educandário', 'calçado', 'nariz', 'irmã',
	'sentimental', 'enlatado', 'cuspir', 'programar', 'quadrúpede', 'jugo', 'mediador', 'rural',
	'hemoglobina', 'quociente', 'malabarista', 'quebra', 'haste', 'arrazoar', 'bravo', 'odor',
	'fatal', 'vigilância', 'guloso', 'beleza', 'retrospectiva', 'jaqueta', 'munição', 'bastante',
	'maneira', 'primogênito', 'estação', 'mordaça', 'aquém', 'levedura', 'frete', 'lágrima',
	'nome', 'dissolver', 'jugular', 'descaso', 'mar', 'comitiva', 'colégio', 'imprevisto',
	'irmão', 'assaltar', 'manual', 'repelente', 'hepatite', 'aplauso', 'piscina', 'hoje',
	'batalhão', 'quarteto', 'balcão', 'fábula', 'clínica', 'ameaça', 'anemia', 'confiança',
	'azul', 'desnaturado', 'xale', 'mobilidade', 'saraivada', 'matemática', 'integridade', 'desconto',
	'bicicleta', 'despedida', 'honesto', 'militar', 'quadro', 'mancha', 'década', 'chaminé',
	'usina', 'quadril', 'novela', 'lasanha', 'jarra', 'filme', 'pupila', 'doação',
	'encontro', 'química', 'hérnia', 'fermento', 'afronta', 'marido', 'expressão', 'endereço',
	'dieta', 'dúzia', 'exposição', 'justificação', 'faísca', 'vocabulário', 'bis', 'perfeccionismo',
	'humanidade', 'meretriz', 'oportunidade', 'ártico', 'encrenca', 'estéril', 'novidade', 'atlântico',
	'tropical', 'café', 'majestade', 'elegância', 'região', 'lavoura', 'turismo', 'profissão',
	'quantidade', 'herança', 'boca', 'rotina', 'adulto', 'expectativa', 'ganância', 'pastel',
	'correspondência', 'legal', 'ação', 'juba', 'dromedário', 'paralisar', 'curtir', 'convite',
	'dueto', 'governador', 'palácio', 'vírgula', 'noite', 'útero', 'inteiro', 'jovem',
	'tempestade', 'quartel', 'quadrilátero', 'pobre', 'lamentação', 'hematoma', 'garçonete', 'comentário',
	'surdez', 'monarca', 'desenho', 'zarabatana', 'infraestrutura', 'qual', 'elevador', 'ocultar',
	'desenvoltura', 'suscetível', 'broa', 'boate', 'bombom', 'humor', 'censura', 'organizar',
	'pirraça', 'joio', 'gravata', 'palavra', 'costume', 'fundamento', 'espuma', 'matinal',
	'noturno', 'conteúdo', 'moleque', 'puxar', 'utilizar', 'arame', 'parabéns', 'boneca',
	'nuvem', 'anzol', 'fisioterapia', 'besteira', 'pente', 'ovelha', 'máximo', 'parlamento',
	'isento', 'bordar', 'moeda', 'lógica', 'miolo', 'dedo', 'polivalente', 'trança',
	'item', 'melodia', 'berço', 'geladeira', 'durante', 'xucro', 'nevasca', 'gabarito',
	'lição', 'perdão', 'virtude', 'cubo', 'polígono', 'reflexão', 'horizonte', 'monopólio',
	'fubá', 'periferia', 'jeito', 'tornozelo', 'esqueleto', 'furto', 'paixão', 'lanche',
	'néscio', 'cardume', 'praça', 'vínculo', 'alpiste', 'delicadeza', 'pacote', 'cofre',
	'obelisco', 'estrangeiro', 'poesia', 'altitude', 'bagulho', 'finalidade', 'distância', 'queratina',
	'porção', 'armazém', 'estante', 'bar', 'propriedade', 'quaresma', 'quieto', 'brigadeiro',
	'bituca', 'páreo', 'sinônimo', 'hotel', 'orquestra', 'hipotenusa', 'substantivo', 'prioridade',
	'porventura', 'manhã', 'jurisdição', 'suspense', 'liberdade', 'competir', 'quitanda', 'joia',
	'negócio', 'normal', 'unir', 'quiosque', 'joça', 'luminosidade', 'alvorada', 'adjetivo',
	'prefeito', 'escafandro', 'asterisco', 'literatura', 'galera', 'duradouro', 'humilhação', 'trivial',
	'útil', 'hidrômetro', 'tabuleiro', 'glicose', 'água', 'força', 'bodas', 'neutro',
	'estrela', 'salubridade', 'motorista', 'estelionatário', 'imperador', 'história', 'original', 'motivo',
	'desilusão', 'base', 'ocasião', 'comunidade', 'piano', 'galpão', 'arremate', 'cachorro',
	'maravilha', 'família', 'pátria', 'tabaco', 'destaque', 'estufa', 'bronze', 'léxico',
	'resgate', 'descoberta', 'gentileza', 'júri', 'enxada', 'fragrância', 'curso', 'ousadia',
	'dragão', 'já', 'recife', 'obscuro', 'sabedoria', 'maná', 'mel', 'bovino',
	'gengiva', 'hidrogênio', 'atmosfera', 'gráfico', 'movimento', 'maca', 'helicóptero', 'nevoeiro',
	'giz', 'presença', 'parque', 'luxo', 'dádiva', 'energia', 'etiqueta', 'bolo',
	'bônus', 'sustentáculo', 'lenha', 'objeto', 'fazenda', 'inauguração', 'noiva', 'cantina',
	'exame', 'pureza', 'ninho', 'província', 'alimento', 'sensibilidade', 'açúcar', 'perseverança',
	'latitude', 'caçarola', 'meta', 'próspero', 'afinal', 'chicote', 'ufa!', 'impacto',
	'gandula', 'faminto', 'esmola', 'jurar', 'questão', 'queijo', 'populacional', 'frio',
	'bebê', 'simplicidade', 'íris', 'frequência', 'exclusividade', 'látex', 'clorofila', 'fome',
	'explosão', 'obediência', 'coroa', 'xodó', 'igreja', 'bruto', 'assinatura', 'zona',
	'quadrangular', 'jovial', 'embora', 'frágil', 'volume', 'vulcão', 'utilitário', 'quiçá',
	'xícara', 'pedido', 'nota', 'sossego', 'cimento', 'necessidade', 'desfrutar', 'oração',
	'fôlego', 'sugestionar', 'metrópole', 'quiproquó', 'nervo', 'labirinto', 'drenar', 'individual',
	'êxtase', 'jamais', 'bíceps', 'quando', 'semelhança', 'rotação', 'hidrante', 'golpe',
	'feijoada', 'batente', 'oxigênio', 'concorrente', 'tabela', 'lâmpada', 'manteiga', 'breve',
	'violência', 'campeonato', 'dúvida', 'incomum', 'perplexo', 'juvenil', 'extravio', 'notícia',
	'festival', 'limpeza', 'joanete', 'balé', 'mãe', 'tornado', 'pêndulo', 'radical',
	'litoral', 'futebol', 'extrato', 'caravana', 'mucosa', 'passageiro', 'duelo', 'amparar',
	'revolução', 'quilo', 'regulamento', 'isca', 'argamassa', 'pedra', 'fúria', 'bafo',
	'ideal', 'destemido', 'floresta', 'junção', 'vantagem', 'salada', 'desastre', 'extremo',
	'dialeto', 'intimidade', 'deserto', 'rústico', 'janela', 'isqueiro', 'investir', 'rosa',
	'escuridão', 'herói', 'hipocrisia', 'trem', 'sábado', 'paciência', 'hino', 'nata',
	'agenda', 'lúcido', 'relógio', 'enfim', 'táxi', 'travessa', 'esposa', 'novilho',
	'cutícula', 'fruta', 'guaraná', 'ordem', 'recreio', 'retrato', 'quadra', 'mercadoria',
	'calcular', 'vinagre', 'favela', 'significado', 'camarote', 'sutileza', 'exuberante', 'plenário',
	'greve', 'guerra', 'surpresa', 'rabisco', 'labareda', 'oásis', 'inferior', 'emprego',
	'bacana', 'lote', 'lã', 'micose', 'ontem', 'paçoca', 'joalheria', 'leite',
	'número', 'granola', 'bisturi', 'planta', 'esfera', 'padaria', 'doutor', 'tanque',
	'independência', 'barco', 'sonâmbulo', 'bússola', 'tarefa', 'petisco', 'julgamento', 'extermínio',
	'embarque', 'carpinteiro', 'quadrilha', 'hemorragia', 'grupo', 'jardim', 'hora', 'bujão',
	'gestante', 'graxa', 'arsenal', 'linguagem', 'caneca', 'nababo', 'usufruto', 'desmaio',
	'distinto', 'subordinado', 'pacífico', 'jirau', 'despensa', 'drible', 'intriga', 'anterior',
	'título', 'bomba', 'linha', 'hipótese', 'coluna', 'gasoduto', 'quarteirão', 'internacional',
	'jazigo', 'hereditário', 'acaso', 'controle', 'natureza', 'felicidade', 'gaiola', 'caatinga',
	'massa', 'ânimo', 'vingança', 'húmus', 'paladar', 'discurso', 'encerrar', 'demais',
	'ilha', 'tutor', 'aldeia', 'vertical', 'ruína', 'personalidade', 'unguento', 'jejum',
	'pleonasmo', 'xará', 'escova', 'marola', 'mulher', 'central', 'federal', 'idade',
	'justo', 'folha', 'errar', 'lábio', 'nação', 'pináculo', 'magnitude', 'droga',
	'medo', 'planejamento', 'beliscar', 'verdade', 'fábrica', 'unilateral', 'paraíso', 'imagem'
);
