(** --------------------------------------------------------------------------------

	This file is part of 'PassGen'.

	'PassGen' is a random password generator.


	License:

	The MIT License (MIT)

	Copyright (c) 2017-2020 Renan Souza da Motta <renansouzadamotta@yahoo.com>

	Permission is hereby granted, free of charge, to any person obtaining a copy of
	this software and associated documentation files (the "Software"), to deal in
	the Software without restriction, including without limitation the rights to
	use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
	the Software, and to permit persons to whom the Software is furnished to do so,
	subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
	FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
	COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
	IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
	CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

	-------------------------------------------------------------------------------- **)
pass_table_5: packed array[0..TABLE_5_SIZE-1] of string = (
	// base 1024
	'example', 'flower', 'stamp', 'lesson', 'fire', 'hand', 'acclaim', 'score', 'moon', 'error',
	'net', 'expensive', 'advance', 'discord', 'impact', 'host', 'gospel', 'fresh', 'cab', 'yolk',
	'padding', 'half', 'duty', 'lynx', 'run', 'nerve', 'bay', 'impeachment', 'sword', 'girl',
	'epoch', 'site', 'burn', 'quiz', 'impress', 'pioneer', 'splash', 'aid', 'peripheral', 'refund',
	'goose', 'jet', 'brave', 'clay', 'pain', 'den', 'impossible', 'secure', 'hope', 'agile',
	'electric', 'hint', 'underline', 'gloss', 'chance', 'container', 'ratio', 'kilometer', 'print', 'machine',
	'fish', 'date', 'cloud', 'proxy', 'fence', 'inch', 'diamond', 'rain', 'nozzle', 'barley',
	'heap', 'bird', 'ground', 'text', 'journal', 'other', 'element', 'quiver', 'quantity', 'owl',
	'clever', 'knock', 'acre', 'user', 'lily', 'rose', 'biology', 'fellow', 'memory', 'omelette',
	'icon', 'spice', 'rest', 'liter', 'office', 'harpoon', 'every', 'color', 'kiosk', 'arcade',
	'fraud', 'yogurt', 'kind', 'nutrient', 'emerge', 'lake', 'vital', 'outdoor', 'order', 'people',
	'boil', 'guard', 'land', 'quintet', 'oneself', 'neighbor', 'car', 'field', 'lazy', 'lot',
	'spring', 'child', 'quiet', 'nurse', 'nut', 'after', 'brazil', 'universe', 'for', 'distinct',
	'coffee', 'chart', 'image', 'impulse', 'indestructible', 'effort', 'manage', 'shop', 'present', 'entry',
	'bless', 'old', 'mystery', 'box', 'nap', 'quartet', 'kink', 'puppy', 'count', 'penalty',
	'serial', 'outfit', 'dye', 'integrity', 'ginger', 'influx', 'noun', 'honor', 'reserve', 'mate',
	'ache', 'divorce', 'excel', 'grocery', 'jolly', 'dog', 'neglect', 'key', 'jump', 'hive',
	'amount', 'boss', 'remedy', 'smell', 'zebra', 'intent', 'effect', 'mud', 'rare', 'laugh',
	'technology', 'villa', 'refined', 'overlay', 'connect', 'own', 'normal', 'labyrinth', 'cable', 'best',
	'jab', 'issue', 'inside', 'idle', 'atom', 'and', 'nitrate', 'advocate', 'energy', 'renew',
	'bus', 'home', 'father', 'notebook', 'distance', 'main', 'first', 'king', 'respect', 'asterisk',
	'original', 'incompetent', 'disclose', 'little', 'forest', 'obscure', 'pack', 'dish', 'maize', 'heaven',
	'lettuce', 'number', 'wedding', 'equivalent', 'outlook', 'near', 'staff', 'leaf', 'xylophone', 'detergent',
	'convey', 'debit', 'integral', 'import', 'butterfly', 'dispel', 'heart', 'quail', 'flux', 'conquer',
	'freedom', 'village', 'harbor', 'destroy', 'aware', 'jar', 'digit', 'razor', 'patience', 'lorry',
	'adore', 'hiccup', 'kernel', 'much', 'air', 'opportunity', 'salt', 'moss', 'guitar', 'overcast',
	'shade', 'obstacle', 'oat', 'word', 'unwanted', 'odyssey', 'caterpillar', 'jute', 'like', 'jug',
	'apple', 'log', 'above', 'picture', 'depot', 'free', 'tree', 'quarter', 'brief', 'hit',
	'gold', 'yesterday', 'deflate', 'off', 'local', 'joy', 'obtain', 'bee', 'barrier', 'retail',
	'support', 'obvious', 'something', 'there', 'perplex', 'xray', 'record', 'ink', 'pineapple', 'yes',
	'baby', 'null', 'bumper', 'ferry', 'unusual', 'bar', 'today', 'level', 'develop', 'disorder',
	'store', 'hip', 'lace', 'lion', 'beloved', 'vacuum', 'build', 'seldom', 'very', 'dream',
	'gnat', 'display', 'unit', 'regular', 'jealous', 'option', 'oatmeal', 'zinc', 'direct', 'department',
	'ring', 'forum', 'analgesic', 'onward', 'device', 'lawn', 'quartz', 'olive', 'amplify', 'plenty',
	'virgin', 'muscle', 'autopsy', 'horizon', 'deal', 'time', 'welcome', 'harm', 'apply', 'mature',
	'syntax', 'enforce', 'work', 'boom', 'aunt', 'ocean', 'how', 'poem', 'pipe', 'any',
	'dance', 'interval', 'incredible', 'axe', 'food', 'eight', 'ask', 'quest', 'road', 'umbrella',
	'pretend', 'mischief', 'marry', 'long', 'misery', 'country', 'inflate', 'hygiene', 'must', 'unreal',
	'juice', 'follow', 'drug', 'inform', 'bacon', 'quadruple', 'team', 'rhyme', 'endeavor', 'sky',
	'chlorine', 'nation', 'sacrifice', 'honey', 'yet', 'canopy', 'medal', 'salary', 'bamboo', 'kilo',
	'death', 'nudge', 'now', 'draft', 'fare', 'luxury', 'inevitable', 'well', 'call', 'income',
	'idea', 'yoga', 'water', 'stick', 'acid', 'bad', 'one', 'emotion', 'jolt', 'nuance',
	'instant', 'hoax', 'river', 'gain', 'comply', 'door', 'allow', 'deciduous', 'gosh', 'age',
	'kingdom', 'noble', 'study', 'district', 'edge', 'draw', 'glossary', 'wife', 'cicada', 'grid',
	'antique', 'tropical', 'comma', 'gunshot', 'away', 'equal', 'jig', 'right', 'limit', 'computer',
	'advice', 'express', 'answer', 'fabric', 'powder', 'under', 'impel', 'citizen', 'havoc', 'soft',
	'fee', 'comfort', 'desk', 'hug', 'understand', 'nugget', 'malady', 'confer', 'disappear', 'hybrid',
	'ado', 'introvert', 'garden', 'young', 'qualm', 'float', 'fruit', 'system', 'light', 'poor',
	'labor', 'afford', 'liar', 'agency', 'industry', 'glide', 'green', 'meal', 'paint', 'mad',
	'valve', 'mountain', 'odd', 'onion', 'civil', 'wait', 'corn', 'game', 'diploma', 'write',
	'forgive', 'quarrel', 'leader', 'lunatic', 'holiday', 'fork', 'need', 'humid', 'invest', 'beauty',
	'xmas', 'price', 'nix', 'keen', 'novel', 'earth', 'consider', 'quick', 'unfold', 'cheese',
	'cement', 'essay', 'random', 'nautical', 'discover', 'oasis', 'beg', 'bold', 'guarantee', 'hero',
	'jam', 'unclear', 'jewel', 'speak', 'yacht', 'good', 'quicksilver', 'microwave', 'love', 'disk',
	'navy', 'great', 'dragon', 'mother', 'reckon', 'kimono', 'domestic', 'immerse', 'alley', 'arid',
	'prompt', 'focus', 'speed', 'funeral', 'file', 'reward', 'race', 'caption', 'miss', 'mercy',
	'contest', 'gravity', 'grain', 'absolutely', 'total', 'property', 'negro', 'extension', 'dummy', 'violin',
	'interest', 'dental', 'kilowatt', 'gross', 'kick', 'acquire', 'nature', 'apex', 'help', 'crayon',
	'eye', 'hurry', 'quality', 'ivy', 'braid', 'condense', 'open', 'fuel', 'central', 'either',
	'biscuit', 'zipper', 'hereby', 'deluge', 'mind', 'cast', 'shovel', 'kill', 'gift', 'granite',
	'remind', 'about', 'suspense', 'organic', 'row', 'alert', 'lap', 'rabbit', 'jacket', 'dry',
	'mite', 'vegetable', 'sheep', 'mayor', 'termite', 'delete', 'quote', 'reproduce', 'arm', 'review',
	'elude', 'bloom', 'outstanding', 'opinion', 'hot', 'yellow', 'floor', 'hunt', 'pause', 'carry',
	'generic', 'needle', 'heat', 'narrow', 'dirt', 'prefix', 'master', 'cure', 'concert', 'private',
	'guest', 'irrigate', 'soon', 'each', 'sound', 'yard', 'craft', 'north', 'nothing', 'pocket',
	'ear', 'inquiry', 'only', 'fair', 'lady', 'birth', 'bullet', 'invent', 'language', 'merchant',
	'gate', 'negotiate', 'neck', 'question', 'cocoa', 'kite', 'legacy', 'photo', 'by', 'detail',
	'puke', 'hazard', 'ketchup', 'snow', 'dive', 'flavor', 'detour', 'herb', 'necessary', 'happen',
	'native', 'grill', 'obsolete', 'gem', 'abbey', 'voyage', 'adjoin', 'find', 'dot', 'embezzle',
	'enough', 'glacial', 'resolve', 'dusk', 'paramount', 'oyster', 'more', 'height', 'repent', 'gallon',
	'judge', 'flag', 'update', 'estimate', 'hue', 'style', 'comment', 'insight', 'keyboard', 'lira',
	'gyve', 'park', 'author', 'even', 'enjoy', 'relative', 'formal', 'white', 'drink', 'repair',
	'precision', 'nest', 'excuse', 'protect', 'blue', 'kayak', 'guzzle', 'compass', 'knot', 'influenza',
	'void', 'defeat', 'imagine', 'howl', 'seven', 'scheme', 'aspire', 'jackpot', 'sympathy', 'address',
	'branch', 'kangaroo', 'able', 'glory', 'tangerine', 'queue', 'cost', 'busy', 'believe', 'loan',
	'genuine', 'delay', 'output', 'oak', 'mix', 'lens', 'incomparable', 'window', 'object', 'omnipotent',
	'papaya', 'add', 'rescue', 'quake', 'round', 'quicksand', 'area', 'kerosene', 'quit', 'raisin',
	'minute', 'magnet', 'echo', 'occult', 'awful', 'jack', 'feature', 'veteran', 'zoo', 'uncle',
	'yield', 'guava', 'karate', 'petrol', 'epic', 'pussy', 'reason', 'milk', 'beware', 'grass',
	'azure', 'bell', 'know', 'brain', 'sea', 'fatal', 'soy', 'nipple', 'give', 'lemon',
	'poison', 'chain', 'brisk', 'gutter', 'okra', 'learn', 'novice', 'who', 'belly', 'region',
	'independence', 'savage', 'event', 'skin', 'revenue', 'skill', 'symbol', 'flee', 'innocent', 'play',
	'zone', 'hi', 'ready', 'individual', 'neutral', 'crystal', 'blink', 'brother', 'access', 'encore',
	'recommend', 'bubble', 'feud', 'victory', 'life', 'vintage', 'assembly', 'day', 'joke', 'knife',
	'quirk', 'worry', 'world', 'astray', 'crime', 'oil', 'drop', 'jelly', 'flame', 'bishop',
	'index', 'bypass', 'axis', 'boat', 'made', 'graceful', 'may', 'hull', 'empty', 'dynamite',
	'use', 'push', 'buffet', 'mug', 'consul', 'castle', 'exhaust', 'elapse', 'hack', 'year',
	'none', 'fact', 'journey', 'mango', 'thing', 'bear', 'name', 'faith', 'quack', 'rude',
	'buy', 'look', 'banner', 'down', 'sponsor', 'bias', 'noise', 'cyanide', 'progress', 'garlic',
	'confirm', 'motor', 'habit', 'cope', 'throne', 'side', 'future', 'christ', 'urban', 'bulk',
	'jocund', 'chaos', 'war', 'party', 'quarantine', 'success', 'hash', 'pray', 'queen', 'strange',
	'red', 'tablet', 'suggest', 'virus', 'target', 'jade', 'drive', 'board', 'gratify', 'library',
	'jury', 'mantle', 'heal', 'status', 'explore', 'nail', 'matter', 'before', 'kindle', 'exit',
	'risk', 'breed', 'job', 'horse', 'music', 'enter', 'cross', 'nymph', 'mane', 'sleeve',
	'into', 'clock', 'outside', 'live', 'luck', 'exile', 'bone', 'increase', 'museum', 'noxious',
	'reef', 'grow', 'inactive', 'profit', 'hundred', 'force', 'ice', 'silver', 'artery', 'vote',
	'alone', 'just', 'infinite', 'keep', 'dwarf', 'complex', 'lonely', 'affect', 'porcupine', 'join',
	'once', 'audible', 'not', 'coax', 'quarry', 'base', 'hair', 'define', 'zeal', 'toilet',
	'balance', 'lacquer', 'kiss', 'peanut', 'guide', 'expert', 'page', 'excess', 'qualify', 'diet',
	'mobile', 'bin', 'wood', 'crucial', 'elite', 'bark', 'loop', 'appeal', 'fox', 'forecast',
	'ransom', 'label', 'controversy', 'justice', 'frisky', 'kidney', 'quite', 'relax', 'glass', 'social',
	'kid', 'firefly', 'spy', 'query', 'gum', 'frost', 'embed', 'over', 'affix', 'cow',
	'mint', 'zip', 'jail', 'honest'
);
